# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperatura.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'temperatura.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperatura.proto\"%\n\x14SolicitudTemperatura\x12\r\n\x05valor\x18\x01 \x01(\x02\">\n\x14ResultadoTemperatura\x12\x11\n\tresultado\x18\x01 \x01(\x02\x12\x13\n\x0b\x64\x65scripcion\x18\x02 \x01(\t2\x9e\x01\n\x14\x43onversorTemperatura\x12\x42\n\x12\x43\x65lsiusAFahrenheit\x12\x15.SolicitudTemperatura\x1a\x15.ResultadoTemperatura\x12\x42\n\x12\x46\x61hrenheitACelsius\x12\x15.SolicitudTemperatura\x1a\x15.ResultadoTemperaturab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperatura_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOLICITUDTEMPERATURA']._serialized_start=21
  _globals['_SOLICITUDTEMPERATURA']._serialized_end=58
  _globals['_RESULTADOTEMPERATURA']._serialized_start=60
  _globals['_RESULTADOTEMPERATURA']._serialized_end=122
  _globals['_CONVERSORTEMPERATURA']._serialized_start=125
  _globals['_CONVERSORTEMPERATURA']._serialized_end=283
# @@protoc_insertion_point(module_scope)
